name: Publish to npm

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v2
      - name: Prepare publish
        id: prep
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Version: $VERSION"
          # handle prerelease
          if [[ $VERSION == *"-"* ]]; then
            DIST_TAG=$(echo $VERSION | sed -E 's/.*-([a-z]+).*/\1/')
            if [[ -z "$DIST_TAG" || "$DIST_TAG" =~ [0-9] ]]; then
              DIST_TAG="next"
            fi
            echo "TAG=--tag $DIST_TAG" >> $GITHUB_OUTPUT
            echo "Detected prerelease version, using tag: $DIST_TAG"
          else
            echo "TAG=" >> $GITHUB_OUTPUT
            echo "Detected stable version, using default latest tag"
          fi
      - run: bun ci
      - run: bun run build --if-present
      - run: bun test
      - run: bunx npm publish ${{ steps.prep.outputs.TAG }} --provenance
